/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as WikiNewRouteImport } from './routes/wiki/new'
import { Route as WikiSlugRouteImport } from './routes/wiki/$slug'
import { Route as EolSlugRouteImport } from './routes/eol/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminEolRouteImport } from './routes/admin/eol'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as WikiEditSlugRouteImport } from './routes/wiki/edit.$slug'
import { Route as AdminSettingsEolRouteImport } from './routes/admin/settings/eol'
import { Route as AdminSettingsCategoriesRouteImport } from './routes/admin/settings/categories'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiNewRoute = WikiNewRouteImport.update({
  id: '/wiki/new',
  path: '/wiki/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EolSlugRoute = EolSlugRouteImport.update({
  id: '/eol/$slug',
  path: '/eol/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEolRoute = AdminEolRouteImport.update({
  id: '/admin/eol',
  path: '/admin/eol',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiEditSlugRoute = WikiEditSlugRouteImport.update({
  id: '/wiki/edit/$slug',
  path: '/wiki/edit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsEolRoute = AdminSettingsEolRouteImport.update({
  id: '/admin/settings/eol',
  path: '/admin/settings/eol',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsCategoriesRoute = AdminSettingsCategoriesRouteImport.update({
  id: '/admin/settings/categories',
  path: '/admin/settings/categories',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/eol': typeof AdminEolRoute
  '/admin/users': typeof AdminUsersRoute
  '/eol/$slug': typeof EolSlugRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki/new': typeof WikiNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/admin/settings/categories': typeof AdminSettingsCategoriesRoute
  '/admin/settings/eol': typeof AdminSettingsEolRoute
  '/wiki/edit/$slug': typeof WikiEditSlugRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/eol': typeof AdminEolRoute
  '/admin/users': typeof AdminUsersRoute
  '/eol/$slug': typeof EolSlugRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki/new': typeof WikiNewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/admin/settings/categories': typeof AdminSettingsCategoriesRoute
  '/admin/settings/eol': typeof AdminSettingsEolRoute
  '/wiki/edit/$slug': typeof WikiEditSlugRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/admin/eol': typeof AdminEolRoute
  '/admin/users': typeof AdminUsersRoute
  '/eol/$slug': typeof EolSlugRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki/new': typeof WikiNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/admin/settings/categories': typeof AdminSettingsCategoriesRoute
  '/admin/settings/eol': typeof AdminSettingsEolRoute
  '/wiki/edit/$slug': typeof WikiEditSlugRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/admin/eol'
    | '/admin/users'
    | '/eol/$slug'
    | '/wiki/$slug'
    | '/wiki/new'
    | '/dashboard/'
    | '/wiki/'
    | '/admin/settings/categories'
    | '/admin/settings/eol'
    | '/wiki/edit/$slug'
    | '/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/admin/eol'
    | '/admin/users'
    | '/eol/$slug'
    | '/wiki/$slug'
    | '/wiki/new'
    | '/dashboard'
    | '/wiki'
    | '/admin/settings/categories'
    | '/admin/settings/eol'
    | '/wiki/edit/$slug'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/admin/eol'
    | '/admin/users'
    | '/eol/$slug'
    | '/wiki/$slug'
    | '/wiki/new'
    | '/dashboard/'
    | '/wiki/'
    | '/admin/settings/categories'
    | '/admin/settings/eol'
    | '/wiki/edit/$slug'
    | '/admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  AdminEolRoute: typeof AdminEolRoute
  AdminUsersRoute: typeof AdminUsersRoute
  EolSlugRoute: typeof EolSlugRoute
  WikiSlugRoute: typeof WikiSlugRoute
  WikiNewRoute: typeof WikiNewRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  WikiIndexRoute: typeof WikiIndexRoute
  AdminSettingsCategoriesRoute: typeof AdminSettingsCategoriesRoute
  AdminSettingsEolRoute: typeof AdminSettingsEolRoute
  WikiEditSlugRoute: typeof WikiEditSlugRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/new': {
      id: '/wiki/new'
      path: '/wiki/new'
      fullPath: '/wiki/new'
      preLoaderRoute: typeof WikiNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eol/$slug': {
      id: '/eol/$slug'
      path: '/eol/$slug'
      fullPath: '/eol/$slug'
      preLoaderRoute: typeof EolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eol': {
      id: '/admin/eol'
      path: '/admin/eol'
      fullPath: '/admin/eol'
      preLoaderRoute: typeof AdminEolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/edit/$slug': {
      id: '/wiki/edit/$slug'
      path: '/wiki/edit/$slug'
      fullPath: '/wiki/edit/$slug'
      preLoaderRoute: typeof WikiEditSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/eol': {
      id: '/admin/settings/eol'
      path: '/admin/settings/eol'
      fullPath: '/admin/settings/eol'
      preLoaderRoute: typeof AdminSettingsEolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/categories': {
      id: '/admin/settings/categories'
      path: '/admin/settings/categories'
      fullPath: '/admin/settings/categories'
      preLoaderRoute: typeof AdminSettingsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  AdminEolRoute: AdminEolRoute,
  AdminUsersRoute: AdminUsersRoute,
  EolSlugRoute: EolSlugRoute,
  WikiSlugRoute: WikiSlugRoute,
  WikiNewRoute: WikiNewRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  WikiIndexRoute: WikiIndexRoute,
  AdminSettingsCategoriesRoute: AdminSettingsCategoriesRoute,
  AdminSettingsEolRoute: AdminSettingsEolRoute,
  WikiEditSlugRoute: WikiEditSlugRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
